import Card from '@components/Card'
import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="relative overflow-auto w-full flex justify-center text-white flex-col items-center flex-wrap h-full text-base">
        <Card className="max-w-lg">
          <br />
          <p className="font-bold">안녕하세요 세현님!</p>
          <p>Merry Christmas!</p>
          <p>당신의 마니또 입니다.</p>
          <br />
          <br />
          <p>즐거운 크리스마스와</p>
          <p>다가올 새해 복 많이 받으세요!</p>
          <br />
          <br />
          <Link
            href="/spin"
            className="flex justify-center items-center w-full h-12 text-white bg-blues-300 rounded-md"
          >
            선물 받기
          </Link>
        </Card>
      </div>
    </>
  )
}
